name = "uptimeflare_worker"
main = "src/index.ts"
compatibility_date = "2025-04-02"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "UPTIMEFLARE_D1"
database_name = "uptimeflare_d1"
database_id = "566e489b-794e-43ee-b85f-4e292511b926"

[[durable_objects.bindings]]
name = "REMOTE_CHECKER_DO"
class_name = "RemoteChecker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RemoteChecker"]

[triggers]
crons = ["* * * * *"]
